## Temporary file to delete the databases.
## Will be obsolete once the database creation is done remotely, automated, and uses the 
## dynamic parameters for prefix and passwords for production.

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_jts TO sa
DROP LOGIN RTC_MikeV_jtsDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_jts
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_jts
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_ccm TO sa
DROP LOGIN RTC_MikeV_ccmDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_ccm
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_ccm
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_qm TO sa
DROP LOGIN RTC_MikeV_qmDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_qm
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_qm
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_rm TO sa
DROP LOGIN RTC_MikeV_rmDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_rm
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_rm
GO
  
ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_dcc TO sa
DROP LOGIN RTC_MikeV_dccDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_dcc
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_dcc
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_lqe TO sa
DROP LOGIN RTC_MikeV_lqeDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_lqe
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_lqe
GO
 
ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_ldx TO sa
DROP LOGIN RTC_MikeV_ldxDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_ldx
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_ldx
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_relm TO sa
DROP LOGIN RTC_MikeV_relmDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_relm
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_relm
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_gc TO sa
DROP LOGIN RTC_MikeV_gcDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_gc
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_gc
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_dw TO sa
DROP LOGIN RTC_MikeV_dwDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_dw
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_dw
GO

ALTER AUTHORIZATION ON DATABASE::RTC_MikeV_csm TO sa
DROP LOGIN RTC_MikeV_csmDBuser
GO
USE master
ALTER DATABASE RTC_MikeV_csm
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE RTC_MikeV_csm
GO


DROP LOGIN RTC_MikeV_dwStoreDBuser
